config/routes.rb
Blogger::Application.routes.draw do
  resources :articles do
    resources :comments
  end

  resources :tags

  root to: "articles#index"
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :taggings
  has_many :tags, :through => :taggings
  has_attached_file :image

  attr_accessor :image

  def tag_list
    self.tags.map do |tag|
      tag.name
    end.join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(", ").map{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.map { |name| Tag.find_or_create_by(:name => name) }
    self.tags = new_or_found_tags
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :author_name, :presence => true
  validates :body, :presence => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, :through => :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :find_article , :only => [:edit, :update, :show, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save

    flash.notice = "Article '#{@article.title}' Created! "

    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update_attributes(article_params)

    flash.notice = "Article '#{@article.title}' Updated! "

    redirect_to articles_path
  end

  def show
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def destroy
    @article.delete

    flash.notice = "Article was Deleted! "

    redirect_to articles_path
  end

  private

  def find_article
    @article = Article.find_by_id(params[:id])
    unless @article
      redirect_to articles_path and return
    end
  end

  def article_params
    params.require(:article).permit(:title, :body, :tag_list)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.save

    redirect_to article_path(@comment.article)
  end

  def destory

  end

  private
  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find_by_id(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article_form.html.erb
<%= form_for(article, :html => {:multipart => true}) do |f| %>
  <ul>
  <% article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/_comments.html.erb
<div>
	<% comments.each do |comment| %>
	<h5>Comment by <%= comment.author_name %></h5>
	<p class="comment"><%= comment.body %></p>
	<p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
	<% end %>
</div>

app/views/articles/edit.html.erb
<h1>Edit <%= @article.title %></h1>

<%= render :partial => "article_form", :locals => { :article => @article }%>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<%= link_to "Create a New Article", new_article_path, :class => "new_article"%>

<ul id="articles">
	<% @articles.each do |article| %>
		<li>
			<%= link_to article.title, article_path(article), :class => "article_title", :id => "article_#{article.id}" %>
			<%= link_to "delete", article_path(article), :method => :delete, :data => {confirm: "Really delete the article?"}%>
		</li>
	<% end %>
</ul>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render :partial => "article_form", :locals => {:article => @article}%>

app/views/articles/show.html.erb
<h1><%= @article.title %></h2>

<p><%= @article.body %></p>
<p><%= link_to "Edit", edit_article_path(@article), :class => "edit_article"%></p>
<p>
	Tags:
	<% @article.tags.each do |tag| %>
		<%= link_to tag.name, tag_path(tag) %>
	<% end %>
</p>

<h3><%= @article.comments.size %> Comments</h3>
<h3>Comments</h3>
<%= render :partial => "articles/comments", :locals => {:comments => @article.comments } %>

<h3>Post a Comment</h3>
<%= render :partial => 'comments/comment_form', :locals => {:article => @article, :comment => @article.comments.new } %>

app/views/comments/_comment_form.html.erb
<%= form_for [ article, comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Your Name" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="flash"><%= flash.notice %></p>
<%= yield %>

</body>
</html>

app/views/tags/index.html.erb
<h2>Show all Tags</h2>

<ul>
	<% @tags.each do |tag| %>
		<li><%= link_to tag.name, tag_path(tag) %></li>
	<% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with '<%= @tag.name %>' </h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>